### ISSUE TITLE
Enable Monitoring (Callbacks) of Serialization Pipeline

### ISSUE THREAD

**Issue by aspektxxx** [ExtendedXmlSerializer/ExtendedXmlSerializer#264] opened 2019-08-30 14:42 UTC
A callback on deserialization for particular object would be very useful (e.g. events hooking). Could be easily achieved by either object implementing specific interface or by decorating method by attribute (e.g. OnDeserializedAttribute like in DataContractSerializer implementation)

**Comment by Mike-EEE** [comment] 2019-09-01 05:10
Funny enough, @aspektxxx this is one of the first concepts I wanted out of a serializer.  Specifically, I wanted to be able to have callbacks for every item that was serialized/deserialized, as well as every property within.

Ironically, of course, I have put every feature _but_ this. 😆  I will see what it will take to do so.

**Comment by Mike-EEE** [comment] 2019-09-14 16:09
Alright @aspektxxx I have a rough draft of this feature put in place.  Check it out:

https://github.com/wojtpl2/ExtendedXmlSerializer/blob/0d4e90b767738c693655196a500d2f916e5d6c23/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue264Tests.cs#L13-L39

Essentially, you can register what I call a composer which can then use the decorator pattern to wrap the original calling serializer with your own serializer and modify the read/write process accordingly.

It's a little different from using attributes, but it should yield the same results.

Please take a look at it and let me know what you think. 👍

**Comment by aspektxxx** [comment] 2019-09-18 14:49
@Mike-EEE Thank you for looking into it. However, your proposal is not able to entirely[OnDeserializing] attribute. It is not possible for object to hookup to events of its properties down the tree. I need to hookup collection changed events, process them somehow and fire new events. This way I would need public method on each such object and go down the tree after deserialization.

**Comment by Mike-EEE** [comment] 2019-09-19 05:05
Ah got it @aspektxxx ...  I have some further ideas around this but will not be able to get to them until next week.  Will check in around that time and see if we can further flesh this out.

**Comment by Mike-EEE** [comment] 2019-10-12 11:16
Apologies for the delay on this.  I've got this on my radar for this weekend and next if needbe. 👍

**Comment by Mike-EEE** [comment] 2019-10-16 17:26
Alright, @aspektxxx sketching this out further.  I've introduced `IDeserializationAware`:

https://github.com/WojciechNagorski/ExtendedXmlSerializer/blob/363b3a25227068c5411defe8eee99531363c2493/src/ExtendedXmlSerializer/ExtensionModel/Instances/IDeserializationAware.cs#L29-L36

You can see that it has three callbacks:

- `OnActivating`: for when the instance has not been activated yet, and only the type is known.
- `OnActivated`: for after when the instance has been activated, but before its contents have been deserialized.  Code executed here is basically like executing it in the class's constructor.
- `OnDeserialized`: This is called when the instance's contents have been fully deserialized.

You can create your own implementation and then register it as shown here:

https://github.com/WojciechNagorski/ExtendedXmlSerializer/blob/363b3a25227068c5411defe8eee99531363c2493/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue264Tests.cs#L28-L79

If you like what you see so far I will continue with creating an `ISerializationAware` equivalent and look to finishing it up as such.

**Comment by Mike-EEE** [comment] 2019-10-16 17:28
Oh, one thing to note is that `OnActivated` does not have a `IFormatReader reader` parameter.  Unfortunately due to the workflow it is not possible to pass this in without a lot of work, so I wanted to post here for feedback before going down that road.

**Comment by Mike-EEE** [comment] 2019-10-19 05:41
Alright, I am feeling pretty good about this feature now.  I have essentially removed `IDeserializationAware` and have replaced it with `ISerializationMonitor`:

https://github.com/WojciechNagorski/ExtendedXmlSerializer/blob/544afa542d0721b9a832091e0c766a93b9e38ec1/src/ExtendedXmlSerializer/ExtensionModel/Instances/ISerializationMonitor.cs#L29-L44

- `OnSerializing`: Called when the serialization process begins on an instance.
- `OnSerialized`: Called when the serialization process finishes on an instance.
- `OnDeserializing`: The first stage of the deserialization process.  This is called at the point when the deserialization process has started on a particular type and has not been activated/created yet.
- `OnActivating`: for when the instance has not been activated yet, and only the type is known.
- `OnActivated`: for after when the instance has been activated, but before its contents have been deserialized.  Code executed here is basically like executing it in the class's constructor.
- `OnDeserialized`: This is called when the instance's contents have been fully deserialized.

Sample code demonstrating this use can be found here:

https://github.com/WojciechNagorski/ExtendedXmlSerializer/blob/544afa542d0721b9a832091e0c766a93b9e38ec1/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue264Tests.cs#L28-L123

Note that you can establish a global/default monitor that monitors each and every type that is de/serialized by the serializer.  _If you use one, this should be defined first_:

https://github.com/WojciechNagorski/ExtendedXmlSerializer/blob/544afa542d0721b9a832091e0c766a93b9e38ec1/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue264Tests.cs#L77

And you can also monitor a specific type with its own monitor:

https://github.com/WojciechNagorski/ExtendedXmlSerializer/blob/544afa542d0721b9a832091e0c766a93b9e38ec1/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue264Tests.cs#L109-L110

If there are no objections/feedback to the current design I will aim to push this out sometime next week.

**Comment by aspektxxx** [comment] 2019-10-23 14:01
@Mike-EEE I did a quick testing today and it looks great! However, I'm getting the `OnDeserialized` callback twice for some objects. Not where is the issue. Will take a look at it tomorrow and let you know.

**Comment by Mike-EEE** [comment] 2019-10-23 16:40
Cool!  Glad to hear that, @aspektxxx. Yeah it's a rough draft so it's expected to be, uh, rough in some areas. 😆  It's probably related to your object graph/model which is undoubtedly more involved than the tests that I have constructed.  If you can provide a quick reproduction with some code it would be greatly appreciated. 👍

**Comment by Mike-EEE** [comment] 2019-11-08 15:55
This has _finally_ been deployed to nuget:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let us know if you run into any issues by opening a new ticket as this is the feature issue.  Closing for now.

**Closed by Mike-EEE** 2019-11-08 15:55 UTC
Labels: enhancement, sample code
